<a href="https://colab.research.google.com/github/SiddheshKukade/tensorflow-template/blob/main/TensorSidAaiBaba.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSORFLOW TUTORIAL
### BY - siddhyaOP



Make sure to use version 2

In [ ]:
%tensorflow_version 2.x  # ONLY REQUIRED FOR THE NOTEBOOK

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.x  # ONLY REQUIRED FOR THE NOTEBOOK`. This will be interpreted as: `2.x`.


TensorFlow 2.x selected.


### Checking the Version

In [ ]:
import tensorflow as tf 

print(tf.__version__)

2.5.0


### **Creating a Tensor**

In [ ]:
 # String Tensor
 String = tf.Variable("Siddesh Bhupendra Kukade " ,tf.string)
 print(String)
 # 2d Tensor 
two = tf.Variable([["d", "sds" ,"weds"] , ["sd", "sd" ,"sdsd"] , ["ok", "ok", "ok"]] , tf.string)
 print(two)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Siddesh Bhupendra Kukade '>
<tf.Variable 'Variable:0' shape=(3, 3) dtype=string, numpy=
array([[b'd', b'sds', b'weds'],
       [b'sd', b'sd', b'sdsd'],
       [b'ok', b'ok', b'ok']], dtype=object)>


In [ ]:
print(tf.rank(two))

tf.Tensor(2, shape=(), dtype=int32)


### ***Shapes of Tensor***

In [ ]:
two.shape

TensorShape([3, 3])

### Changing the Shape of Tensor




1.   Ones



In [1]:
t1 = tf.ones([1,2,5])
t1

NameError: name 'tf' is not defined




2.   Reshape



In [ ]:
t2 = tf.reshape(t1, [5,2,1])
t2

<tf.Tensor: shape=(5, 2, 1), dtype=float32, numpy=
array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]], dtype=float32)>

In [ ]:
t3 = tf.reshape(t2  , [2,5,1]) # same output for t1 and t2 as the No of Elements are same i.e 10 elements.
t3

<tf.Tensor: shape=(2, 5, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]], dtype=float32)>

**Auto Reshape**

In [ ]:
t3 = tf.reshape(t3  , [2,5,-1]) # -1 cell is automatically reshapes the Tensor 
t3

<tf.Tensor: shape=(2, 5, 1), dtype=float32, numpy=
array([[[-1.],
        [-1.],
        [-1.],
        [-1.],
        [-1.]],

       [[-1.],
        [-1.],
        [-1.],
        [-1.],
        [-1.]]], dtype=float32)>

# Types of **Tensors**

1.   Variable
2.   Constants
3.   Placeholder
4.   SparseTensor

With the execption of ```Variable``` all these tensors are immuttable, meaning their value may not change during execution.

For now, it is enough to understand that we use the Variable tensor when we want to potentially change the value of our tensor.

## Evaluating Tensors


In [ ]:
with tf.Session() as sess : 
  tensor.eval()

AttributeError: ignored